name: MinecartChestFilter
main: com.github.Kory33.minecartchestfilter.core.MinecartChestFilter
version: 0.1.1

commands:
    spawnFilteredStorageMinecart:
        description: spawn filtered minecart at the location where the player is standing
        usage: /spawnFilteredStorageMinecart <type>
        aliases: spawnfsminecart
        permission: filteredstorageminecart.spawn
        permission-message: You do not have /<permission> to execute this command

permissions:
    filteredstorageminecart.*:
        description: Gives all access to spawnFilteredStorageMinecart commands
        children:
            filteredstorageminecart.spawn: true
    filteredstorageminecart.spawn:
        description: Allows you to spawn filtered minecart
        default: op
